module ComponentProvider{
                domain xp;
                subdomain yp;

                provided interface IProvider{
                     void iniciaGraficos(in short modo)
                     { pre: modo<>77.
                       post: modo<1683.
                     };
                     void shortextxy(in short x, in short y, in char num, in short collet, in short colorfon,in short tam)
                     { pre: tam<=82.
                       post: collet==244.
                     };
                     short eliminaPoli(out char b)
                     { pre: b<=66.
                       post: b<2266.
                     };
                     short insertaDatB(out char a, out float c, in double e)
                     { pre: c>=40.
                       post: a>1257.
                     };
                     short creanodoPoli(out char b, out double c,in short e)
                     { pre: c<49.
                       post: b>3413.
                     };
                     float evalua(out char b,out double xm)
                     { pre: xm<79.
                       post: xm==3342.
                     };
                     void captionmat(out double matriz,in short n,in short cual)
                     { pre: matriz>2.
                       post: n>3701.
                     };
                     void changeLine(out double matriz, in short ren, in short col, in short n)
                     { pre: col>96.
                       post: matriz>=3142.
                     };
                     void llenacero(out double matriz, in short n)
                     { pre: matriz<=35.
                       post: matriz>2426.
                     };
                     void menu();
                     void ventMenu();
                     void ventanaCaptura(in short x1,in short y1,in short x2,in short y2)
                     { pre: y2>27.
                       post: x1<>3349.
                     };
                     long calculaFactorial(in short n)
                     { pre: n>=99.
                       post: n>=490.
                     };
                     void factorial();
                     void captDatB(out char a,in short cual)
                     { pre: cual<>51.
                       post: a>2960.
                     };
                     void captDatBiseccion(out char a)
                     { pre: a<10.
                       post: a<>4015.
                     };
                     float biseccion(out char i,out float a,out float b,out float tol,out float ant)
                     { pre: i<95.
                       post: b==4366.
                     };
                     void captDatRegFalsa(out char a)
                     { pre: a<>49.
                       post: a>4211.
                     };
                     float regFalsa(out char i,out float a,out float b,out float tol,out float ant)
                     { pre: b<>55.
                       post: a<>2840.
                     };
                     float gaussJordan(out double matriz, in short n)
                     { pre: n>=45.
                       post: matriz==3813.
                     };
                     void inprimeJordan(out float matriz,out float nuevo,in short n,in short op,in short cual)
                     { pre: matriz>=64.
                       post: cual<=1012.
                     };
                     float gaussSeidel(out float matriz,in short n,out float tol)
                     { pre: n<=18.
                       post: n<3774.
                     };
                     void inprimeSeidel(out double nuevo,in short n)
                     { pre: n<>10.
                       post: nuevo>3203.
                     };
                     short cumple(out float matriz,in short r, in short ren,in short n )
                     { pre: n<>59.
                       post: ren<>3203.
                     };
                     short converge(out float matriz,in short n)
                     { pre: n>8.
                       post: matriz<=3031.
                     };
                     void sustituyeAtras(out float lu,in short n,out float vector)
                     { pre: n<94.
                       post: vector>3862.
                     };
                     float sustituyeade(out float lu, in short n)
                     { pre: n==23.
                       post: n>3923.
                     };
                     short crealu(out float lu,out float mat,in short n)
                     { pre: n<>91.
                       post: n>262.
                     };
                     void pushatend(out float head,out float addx,out float addxy)
                     { pre: head==36.
                       post: head<>732.
                     };
                     void freei(out char cab)
                     { pre: cab==74.
                       post: cab==138.
                     };
                     void ajustacurva(out double cab)
                     { pre: cab<=61.
                       post: cab<51.
                     };
                     void minimosCuadrados();
                     void derivamenu();
                     float derivacion(out short arre ,in short n)
                     { pre: arre>=12.
                       post: n>3002.
                     };
                     void simpson();
                     void lagrange();
                     void metodoLagrange();
                     void lagrange(out float punto, in short n)
                     { pre: punto>=16.
                       post: punto>=1153.
                     };
                     void leedato(in char a,in short x,in short y,in short n)
                     { pre: x<54.
                       post: n<>4416.
                     };
                     void shortegracionNumerica();
                     void iniciaraton();
                     void encienderaton();
                     short botonraton();
                     short botonratonx();
                     short botonratony();
                     void limitaratonx(in short x1,in short x2)
                     { pre: x1<50.
                       post: x1>=4465.
                     };
                     void limitaratony(in short y1,in short y2)
                     { pre: y2<>35.
                       post: y1==4212.
                     };
                     void cierraraton();
                     short verificaboton(out char cab,in short botomx,in short botomy)
                     { pre: botomy<10.
                       post: cab<3258.
                     };
                     void botonlista(out float cab, in float datos)
                     { pre: cab==46.
                       post: cab<2511.
                     };
                     short method940(in short x,in long y)
                     { pre: x<>86.
                       post: y<>4324.
                     };
                     long method527(in void x,out short y)
                     { pre: x>=34.
                       post: y<211.
                     };
                     long method1795(out float x,inout void y)
                     { pre: x<45.
                       post: x<>2956.
                     };
                     short method25626(out short x,out short y)
                     { pre: x<>43.
                       post: y<>2610.
                     };
                     void method1048(out void x,inout float y)
                     { pre: y<>18.
                       post: y>=2246.
                     };
                     float method783(out short x,inout short y)
                     { pre: y>0.
                       post: x>=403.
                     };
                     short method10(in float x,out short y)
                     { pre: x<>86.
                       post: y<380.
                     };
                     void method304(in long x,in short y)
                     { pre: x>=87.
                       post: x<2660.
                     };
                     long method25674(in void x,inout short y)
                     { pre: y<=21.
                       post: y==1202.
                     };
                     short method744(in float x,out float y)
                     { pre: y==90.
                       post: x<1804.
                     };
                     short method612(in void x,out void y)
                     { pre: y>=38.
                       post: y<2758.
                     };
                     long method483(in short x,out float y)
                     { pre: x<=59.
                       post: y<>23.
                     };
                     short method107(inout long x,out float y)
                     { pre: x>=2.
                       post: x==3704.
                     };
                     short method183(in short x,out long y)
                     { pre: y>=82.
                       post: x>3081.
                     };
                     long method25856(in void x,out void y)
                     { pre: y<70.
                       post: y>16.
                     };
                     short method175(in short x,out float y)
                     { pre: x<55.
                       post: y==3370.
                     };
                     float method25939(in short x,out long y)
                     { pre: x<>78.
                       post: x<=422.
                     };
                     long method373(out float x,out float y)
                     { pre: x<>70.
                       post: y<1355.
                     };
                     void method1207(out void x,inout void y)
                     { pre: x==66.
                       post: y<1232.
                     };
                     short method865(inout long x,out void y)
                     { pre: y<>3.
                       post: y<3611.
                     };
                     void Persona(in short d,in short e)
                     { pre: d<>90.
                       post: e==4028.
                     };
                     long method876(in float x,out long y)
                     { pre: x<=28.
                       post: x==216.
                     };
                     float method182(in short x,out short y)
                     { pre: y<>90.
                       post: y<3295.
                     };
                     float method1734(in long x,in void y)
                     { pre: y<=19.
                       post: x==1525.
                     };
                     short srand(in short feed)
                     { pre: feed<>52.
                       post: feed>=1677.
                     };
                     void fireEditingStopped(in boolean edit)
                     { pre: edit>=42.
                       post: edit<2428.
                     };
                     void method25387(out long x,inout long y)
                     { pre: y>=8.
                       post: y==2852.
                     };
                     short method968(in float x,out void y)
                     { pre: x>=46.
                       post: y>1050.
                     };
                     short method32(in float x,out void y)
                     { pre: y<88.
                       post: y==631.
                     };
                     long method948(in void x,in float y)
                     { pre: y<>20.
                       post: y<3329.
                     };
                     short method103(in void x,out long y)
                     { pre: y<>29.
                       post: y>=362.
                     };
                     long method25385(out short x,out long y)
                     { pre: y==77.
                       post: x<3031.
                     };
                     float method1524(in long x,in short y)
                     { pre: y>15.
                       post: x<1002.
                     };
                     float method25502(inout long x,in long y)
                     { pre: x>72.
                       post: x==3836.
                     };
                     long method530(inout float x,inout void y)
                     { pre: x==37.
                       post: y<=1935.
                     };
                     float method889(in short x,inout void y)
                     { pre: y<=4.
                       post: x<3959.
                     };
                     void method810(in long x,out short y)
                     { pre: y<>0.
                       post: x==387.
                     };
                     short method989(inout void x,out long y)
                     { pre: y<=5.
                       post: y<=230.
                     };
                     float method151(out void x,in float y)
                     { pre: x>=50.
                       post: x>=2670.
                     };
                     short method177(in void x,out short y)
                     { pre: x<=36.
                       post: x<=1503.
                     };
                     float method25472(in void x,in long y)
                     { pre: x==94.
                       post: x<>3831.
                     };
                     void method5395(out long x,in short y)
                     { pre: y<>12.
                       post: y<>3447.
                     };
                     void method1191(out void x,out long y)
                     { pre: x<3.
                       post: x<>3779.
                     };
                     long method1037(in long x,out short y)
                     { pre: y<59.
                       post: x>1183.
                     };
                     short method160(out float x,out long y)
                     { pre: x>=75.
                       post: x<>1202.
                     };
                     long method1349(in short x,out short y)
                     { pre: x==97.
                       post: x>=2856.
                     };
                     void method1269(out float x,in short y)
                     { pre: x<>65.
                       post: x<4377.
                     };
                     long method1316(in short x,out void y)
                     { pre: x<>29.
                       post: x>=3533.
                     };
                     long method496(in void x,out void y)
                     { pre: x<=82.
                       post: y==4436.
                     };
                     long method563(in long x,in float y)
                     { pre: y==76.
                       post: y==2720.
                     };
                };
};
