module ComponentRequired{
                domain xr;
                subdomain yr;

                required interface IRequired{
                     void iniciaGraficos(in short modo)
                     { pre: modo>90.
                       post: modo>=2706.
                     };
                     void shortextxy(in short x, in short y, in char num, in short collet, in short colorfon,in short tam)
                     { pre: x==32.
                       post: tam==3208.
                     };
                     short eliminaPoli(out char b)
                     { pre: b==2.
                       post: b<>1941.
                     };
                     short insertaDatB(out char a, out float c, in double e)
                     { pre: e<61.
                       post: a<=3279.
                     };
                     short creanodoPoli(out char b, out double c,in short e)
                     { pre: c==75.
                       post: b<4189.
                     };
                     float evalua(out char b,out double xm)
                     { pre: b>26.
                       post: xm<2360.
                     };
                     void captionmat(out double matriz,in short n,in short cual)
                     { pre: cual<>44.
                       post: n<>755.
                     };
                     void changeLine(out double matriz, in short ren, in short col, in short n)
                     { pre: n>62.
                       post: n>3127.
                     };
                     void llenacero(out double matriz, in short n)
                     { pre: matriz>69.
                       post: matriz>=3252.
                     };
                     void menu();
                     void ventMenu();
                     void ventanaCaptura(in short x1,in short y1,in short x2,in short y2)
                     { pre: x2>=11.
                       post: y2<=4452.
                     };
                     long calculaFactorial(in short n)
                     { pre: n<=38.
                       post: n<>2869.
                     };
                     void factorial();
                     void captDatB(out char a,in short cual)
                     { pre: a<=46.
                       post: a<=4219.
                     };
                     void captDatBiseccion(out char a)
                     { pre: a<47.
                       post: a<>2730.
                     };
                     float biseccion(out char i,out float a,out float b,out float tol,out float ant)
                     { pre: b<=0.
                       post: b<3589.
                     };
                     void captDatRegFalsa(out char a)
                     { pre: a>=48.
                       post: a>=2994.
                     };
                     float regFalsa(out char i,out float a,out float b,out float tol,out float ant)
                     { pre: ant<=15.
                       post: b>1380.
                     };
                     float gaussJordan(out double matriz, in short n)
                     { pre: n<39.
                       post: n>1401.
                     };
                     void inprimeJordan(out float matriz,out float nuevo,in short n,in short op,in short cual)
                     { pre: matriz<11.
                       post: nuevo<>3135.
                     };
                     float gaussSeidel(out float matriz,in short n,out float tol)
                     { pre: n>=37.
                       post: matriz==3501.
                     };
                     void inprimeSeidel(out double nuevo,in short n)
                     { pre: n==49.
                       post: nuevo<3327.
                     };
                     short cumple(out float matriz,in short r, in short ren,in short n )
                     { pre: matriz<>83.
                       post: n>152.
                     };
                     short converge(out float matriz,in short n)
                     { pre: n<>39.
                       post: matriz<>3776.
                     };
                     void printshortimage(inout char title, in float width, in float border, in float bordertopinches,in short left, in short right, in short right, in short bottom, in boolean active)
                     { pre: title>31.
                       post: width<280.
                     };
                     short method1380(out long x,inout void y)
                     { pre: y<>28.
                       post: x<>2319.
                     };
                     short method389(in float x,out long y)
                     { pre: x==10.
                       post: y==1700.
                     };
                     void method25711(in void x,in float y)
                     { pre: x==82.
                       post: x<>1691.
                     };
                     short registerbgifont( out char font )
                     { pre: font>82.
                       post: font>3444.
                     };
                     void method25511(in long x,out long y)
                     { pre: y<>67.
                       post: x<3589.
                     };
                     float method1672(out long x,inout long y)
                     { pre: x<89.
                       post: x==2712.
                     };
                     float method25568(in long x,in float y)
                     { pre: y<>69.
                       post: y<3398.
                     };
                     float method5394(in short x,inout long y)
                     { pre: y>=61.
                       post: x<>1629.
                     };
                     void method596(in short x,out float y)
                     { pre: x<=13.
                       post: y==2698.
                     };
                     void 	removeChangeListener(in char l)
                     { pre: l==29.
                       post: l<3081.
                     };
                     long method1467(in float x,out float y)
                     { pre: x<=17.
                       post: x<=2142.
                     };
                     void method25876(inout long x,out float y)
                     { pre: y<8.
                       post: y==2913.
                     };
                     long method777(in long x,out short y)
                     { pre: y<0.
                       post: y>=3006.
                     };
                     long method881(inout long x,out float y)
                     { pre: y>95.
                       post: y<>2327.
                     };
                     long method1362(out short x,out long y)
                     { pre: y==69.
                       post: x==1873.
                     };
                     short method979(in long x,out void y)
                     { pre: y<>94.
                       post: y>=20.
                     };
                     long method1163(in float x,in long y)
                     { pre: y>73.
                       post: x<>1869.
                     };
                     long method25356(out float x,out void y)
                     { pre: y>=63.
                       post: x<>3781.
                     };
                     short method514(in float x,out long y)
                     { pre: x>66.
                       post: x>=1916.
                     };
                     short method203(in void x,out long y)
                     { pre: x<>86.
                       post: x<1169.
                     };
                     float method1014(out short x,in float y)
                     { pre: x==65.
                       post: y<=2681.
                     };
                     short method25743(in void x,out short y)
                     { pre: x<>88.
                       post: x>=4370.
                     };
                     float method1097(out short x,in short y)
                     { pre: y>=20.
                       post: y>2636.
                     };
                     void method741(in float x,out long y)
                     { pre: x==77.
                       post: x<1933.
                     };
                };
};
