module ComponentProvider{
                domain xp;
                subdomain yp;

                provided interface IProvider{
                     void iniciaGraficos(in short modo)
                     { pre: modo>90.
                       post: modo==3528.
                     };
                     void shortextxy(in short x, in short y, in char num, in short collet, in short colorfon,in short tam)
                     { pre: num==9.
                       post: y<>4024.
                     };
                     short eliminaPoli(out char b)
                     { pre: b<>10.
                       post: b==1862.
                     };
                     short insertaDatB(out char a, out float c, in double e)
                     { pre: a==79.
                       post: c>538.
                     };
                     short creanodoPoli(out char b, out double c,in short e)
                     { pre: c<58.
                       post: e<1418.
                     };
                     float evalua(out char b,out double xm)
                     { pre: xm==30.
                       post: xm<1805.
                     };
                     void captionmat(out double matriz,in short n,in short cual)
                     { pre: n<=33.
                       post: cual>=3257.
                     };
                     void changeLine(out double matriz, in short ren, in short col, in short n)
                     { pre: n>77.
                       post: ren>=759.
                     };
                     void llenacero(out double matriz, in short n)
                     { pre: n>=6.
                       post: matriz<3791.
                     };
                     void menu();
                     void ventMenu();
                     void ventanaCaptura(in short x1,in short y1,in short x2,in short y2)
                     { pre: x2<=67.
                       post: y1>1081.
                     };
                     long calculaFactorial(in short n)
                     { pre: n<=95.
                       post: n<>2906.
                     };
                     void factorial();
                     void captDatB(out char a,in short cual)
                     { pre: cual<>18.
                       post: a>42.
                     };
                     void captDatBiseccion(out char a)
                     { pre: a==63.
                       post: a<=3074.
                     };
                     float biseccion(out char i,out float a,out float b,out float tol,out float ant)
                     { pre: i>=37.
                       post: i<=531.
                     };
                     void captDatRegFalsa(out char a)
                     { pre: a==25.
                       post: a>=3786.
                     };
                     float regFalsa(out char i,out float a,out float b,out float tol,out float ant)
                     { pre: b>=48.
                       post: i>=302.
                     };
                     float gaussJordan(out double matriz, in short n)
                     { pre: matriz==27.
                       post: n<=2318.
                     };
                     void inprimeJordan(out float matriz,out float nuevo,in short n,in short op,in short cual)
                     { pre: op>=81.
                       post: nuevo<=4146.
                     };
                     float gaussSeidel(out float matriz,in short n,out float tol)
                     { pre: matriz>=79.
                       post: matriz>=2764.
                     };
                     void inprimeSeidel(out double nuevo,in short n)
                     { pre: n>=68.
                       post: n<>1981.
                     };
                     short cumple(out float matriz,in short r, in short ren,in short n )
                     { pre: r<>61.
                       post: n>2301.
                     };
                     short converge(out float matriz,in short n)
                     { pre: matriz<42.
                       post: n<>542.
                     };
                     void sustituyeAtras(out float lu,in short n,out float vector)
                     { pre: lu<=66.
                       post: vector<=3602.
                     };
                     float sustituyeade(out float lu, in short n)
                     { pre: lu<6.
                       post: lu<789.
                     };
                     short crealu(out float lu,out float mat,in short n)
                     { pre: n<=46.
                       post: mat==1927.
                     };
                     void pushatend(out float head,out float addx,out float addxy)
                     { pre: addx<=66.
                       post: addx>3345.
                     };
                     void freei(out char cab)
                     { pre: cab<=14.
                       post: cab==366.
                     };
                     short method337(inout short x,inout short y)
                     { pre: y<69.
                       post: x==36.
                     };
                     void setmousequeuestatus( in short kind, in boolean status )
                     { pre: kind<=45.
                       post: status<>3379.
                     };
                     short method464(inout short x,in long y)
                     { pre: x<86.
                       post: y>=806.
                     };
                     long method730(inout short x,inout long y)
                     { pre: x==0.
                       post: x<>23.
                     };
                     float method577(in float x,out float y)
                     { pre: x<=0.
                       post: y<=1535.
                     };
                     float method893(out void x,out void y)
                     { pre: x==15.
                       post: x<>4157.
                     };
                     float tan(in float r )
                     { pre: r>=36.
                       post: r<=1121.
                     };
                     float method603(in void x,out void y)
                     { pre: y<=22.
                       post: y==1841.
                     };
                     float method975(inout short x,in short y)
                     { pre: y<>98.
                       post: x<4130.
                     };
                     long method902(in void x,out float y)
                     { pre: y>=94.
                       post: x<3503.
                     };
                     void circle( in short x, in short y, in short radius )
                     { pre: x==59.
                       post: radius>=2936.
                     };
                     void method128(inout long x,in float y)
                     { pre: y==17.
                       post: y>=3785.
                     };
                     float method901(in long x,out long y)
                     { pre: y==5.
                       post: y==3302.
                     };
                     void method53(in void x,out short y)
                     { pre: x==76.
                       post: y>3545.
                     };
                     void method25875(out short x,inout long y)
                     { pre: y<61.
                       post: x==2771.
                     };
                     void method1545(in short x,inout long y)
                     { pre: y==1.
                       post: x<>1301.
                     };
                     void processItemEvent(inout char e)
                     { pre: e==3.
                       post: e<=1509.
                     };
                     void method574(inout short x,out long y)
                     { pre: y>=66.
                       post: x>622.
                     };
                     short method940(in short x,in long y)
                     { pre: y>50.
                       post: x<=1010.
                     };
                     short method1925(in float x,inout long y)
                     { pre: y>45.
                       post: y<1626.
                     };
                };
};
