 module ATM{    
        domain            Bank;
        subdomain       Atm;     
        
        provided interface IAtmService{
            oneway void locateBank();   
                         long createSession();            
                         long balance();
                         long creditLimit();
        };
        required interface IAtmClient{
            long deposit(in short amount, in short numclient)
            {  pre: amount > 0 .
               post: selfamount = selfamount + amount .
            };
            void withdrawal(in short cardnumber, in string password, in short amount)
            {  pre: amount > amount .
               pre: password <> empty .
               pre: validCard(cardno) == true .
               post: amount = amount  - amount .   
               post: validCard(cardno) == true .
            };
            void locateNetwork();
        };
};
